# Generated by Django 5.2.8 on 2025-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('uni', models.CharField(max_length=1000)),
                ('field', models.CharField(max_length=1000)),
                ('passw', models.CharField(max_length=1000)),
            ],
        ),
    ]
